name: Download LSPosed Artifacts

on:
  workflow_dispatch:

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout LSPosed repository
        uses: actions/checkout@v2
        with:
          repository: JingMatrix/LSPosed
          path: LSPosed

      - name: List runs
        id: list-runs
        uses: actions/github-script@v5
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: 'JingMatrix',
              repo: 'LSPosed',
              per_page: 1,
              status: 'success'
            });
            core.setOutput('run_id', runs.data.workflow_runs[0].id);
          
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: Build.yml # Replace with actual workflow filename
          run_id: ${{ steps.list-runs.outputs.run_id }}
          name: artifact-name # Replace with actual artifact name
          path: ./artifacts

      - name: Upload Artifacts to this repository
        uses: actions/upload-artifact@v2
        with:
          name: LSPosed-artifacts
          path: ./artifacts
